# 当前配置文件环境为：dev
server:
  port: 10240
  servlet:
    context-path: /api
    session:
      timeout: 30m
spring:
  config:
    activate:
      on-profile: dev
  # 数据源基本配置
  datasource:
    username: postgres
    password: poZX0912<>?
    url: jdbc:postgresql://110.42.133.216:5432/app?useSSL=false
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # Druid配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
  # redis配置
  redis:
    host: 110.42.133.216
    port: 6379
    password: 123456
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

# 日志配置
logging:
  level:
    root: info
    com.baomidou.mybatisplus.core.metadata.TableInfoHelper: error
